### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by kyri0** [thirdy/durian#63] opened 2016-01-30 08:39 UTC
I keep complaining that GGG doesn't add a tutorial for new players, and in some ways, Durian is like PoE, having an initial steep learning curve, so I believe we should have a tutorial for how Durian works, and a FAQ.

I think this tutorial should be in Durian, like be showed as a pop up when you open it (with an option to not show it again). Or just put it in the help tab, anyway.

I'll start writing one today, but if you guys wanna give it a help, please post here what you think that should be in it, especially in the FAQ.

**Comment by Dominik-O22** [comment] 2016-01-30 10:34
Some information on how mod groups work would be great

**Comment by kyri0** [comment] 2016-01-30 17:31
@zocke1r Indeed. For now, untill @thirdy comes up with a better way to search for mod groups, they're really complicated to do. Well, not to search, that's actually easy, you just need to type the term, but to create them. I was trying to come up with a way to explain some of it to you, but it's simply beyond me to clarify it. I'm sorry. I believe that it wasn't explained by thirdy yet exactly because it's just to complicated.

**Comment by kyri0** [comment] 2016-01-30 20:42
Finished the first draft: [https://www.pathofexile.com/forum/view-thread/1507190/page/15/#p12733334](url)

@thirdy if you could add it to the first post would be great. Just quote everything in a spoiler tag, so it won't make the post gigantic.

**Comment by zocke1r** [comment] 2016-01-31 14:01
how do i search for map tiers?

**Comment by kyri0** [comment] 2016-01-31 15:00
@zocke1r I got a notification with the following question:

"how do i search for map tiers?"

That's actually a very good question. Right now, poe.trade handles tier lvl and gem lvl as being the same thing. So, to search for a tier lvl, you would have to use the term 'glvl'. But you'll also have to add `map                 =       name=Map` in your .txt term files, so you can search like 'map glvl 10', and it will only show tier 10+ maps. I'll change the regex for it to reflect both searches.

**Comment by Dominik-O22** [comment] 2016-01-31 15:03
i did that already in pull request #60 among other things, yeahi posted it but after realizing that poe.trade handles it like that i removed the question and just modified my terms file to reflect that

**Comment by kyri0** [comment] 2016-01-31 15:30
Lol, you're fast. Btw, you came up with the same regex I did here, but it didn't work for me. Have you tried it there? What I can see here is when I add the '?' to make the characters optional, it stops working.

**Comment by Dominik-O22** [comment] 2016-01-31 18:13
well i check most of my regex using regexr.com to see if they work as intended, which 
`(g(em)?le?ve?l|(Map)?t(ier)?)(\d+)`
does match against all desired possibilities, the problem is group1 is no longer the number part, group 5 is and for the range it is group 5 and 6

**Comment by thirdy** [comment] 2016-02-01 04:51
note that you can specify which group you want to get.

for example, this can be :

glvl(\d{1,2})-(\d{1,2})-(\d{1,2})             =       level_min=$GROUP2&level_max=$GROUP3

crude example sorry.

The logic here is that for,

`level_min=$GROUP2&level_max=$GROUP3`

the place holders $GROUP2 and $GROUP3 would be read as the regex group 2 and 3. You can have as many as group you want even $GROUP99999 (up to the limit of an int in java which is about 2.1 billion. Formally the syntax is $GROUPn where n is the regex group number.

also btw,

$MG 

is replaced by:

group_type=And&group_min=&group_max=&group_count=1

Cheers @kyri0 @zocke1r

**Comment by Dominik-O22** [comment] 2016-02-01 06:56
thank you for that information as to what $MG represents

**Comment by thirdy** [comment] 2016-02-21 01:45
Tutorial written by kyrio now in:
https://www.pathofexile.com/forum/view-thread/1507190/page/1#p12199139
closing

**Closed as completed by thirdy** 2016-02-21 01:45 UTC
Labels: enhancement
